main = "./src/index.ts"
compatibility_date = "2022-02-14"

[env.dev]
name = "flarelytics-dev"

[env.dev.vars]
DB_NAME = "dev"

[env.production]
name = "flarelytics"

[env.production.vars]
DB_NAME = "production"

# [secrets]
# DATABASE_HOST
# DATABASE_USERNAME
# DATABASE_PASSWORD
